name: AI Day 2026 - Generate PDF

on:
  push:
    branches: [ main ]
    paths:
      - '*.md'
      - '.github/workflows/generatepdf.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Generate pdf
      run: |
        for deck in 'presentation' 'presentation30min'; do
          cp "$deck.md" "$deck-backup.md"
          sed -i "s/%date%/$(date +'%Y-%m-%d')/g" "$deck.md"
          sed -i "s/%time%/$(date +'%H:%M')/g" "$deck.md"
          npx @marp-team/marp-cli@latest "$deck.md" --pdf --allow-local-files --pdf-outlines --pdf-outlines.pages=false
          rm "$deck.md"
          mv "$deck-backup.md" "$deck.md"
        done

    - name: commit & push
      run: |
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update slides"
        git push

